version: '3'

volumes:
  pg_data_kittygram:
  static_kittygram:
  media_kittygram:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
  backend:
    image: 2fab4uz/kittygram_backend
    volumes:
      - static_kittygram:/backend_static
      - media_kittygram:/media
    depends_on:
      - db
    env_file: .env
  frontend:
    env_file: .env
    image: 2fab4uz/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_kittygram:/frontend_static
  gateway:
    image: 2fab4uz/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_kittygram:/static
      - media_kittygram:/media
